services:
  mongo_db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - elt_cluster
  
  nifi:
    container_name: nifi
    build: ./Dockerfiles/nifi
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456789101112
      - NIFI_JVM_HEAP_MAX=2g
    volumes:
      - nifi-data:/opt/nifi/nifi-current/Data
    ports:
      - 8443:8443
      - 5200:5200
    networks:
      - elt_cluster
    depends_on:
      - namenode
      
  namenode:
    build: ./Dockerfiles/hdfs/namenode
    container_name: namenode
    environment:
      - CLUSTER_NAME=elt_cluster
    ports:
      - "9870:9870"
      - "9000:9000"
      - "50070:50070"
      - "8020:8020"
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - elt_cluster

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=2
    depends_on:
      - namenode
    volumes:
      - datanode1-data:/hadoop/dfs/data
    networks:
      - elt_cluster

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=2
    depends_on:
      - namenode
    volumes:
      - datanode2-data:/hadoop/dfs/data
    networks:
      - elt_cluster

  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark_network
      - elt_cluster

  spark-worker:
    image: bitnami/spark:3.5.1
    deploy:
      replicas: 2
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081-8101:8081"
    networks:
      - spark_network

volumes:
  namenode-data:
  datanode1-data: 
  datanode2-data: 
  nifi-data:

networks:
  elt_cluster:
    driver: bridge
  spark_network:
    driver: bridge
  