services:
  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=elt_cluster
    ports:
      - "9870:9870"
      - "9000:9000"
      - "50070:50070"
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - elt_cluster

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    volumes:
      - datanode1-data:/hadoop/dfs/data
    networks:
      - elt_cluster

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    volumes:
      - datanode2-data:/hadoop/dfs/data
    networks:
      - elt_cluster

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:

networks:
  elt_cluster:
    driver: bridge