apiVersion: 1
datasources:
  - id: 1
    uid: "bdo551wz4pddsc"
    orgId: 1
    name: "yesoreyeram-infinity-datasource"
    type: "yesoreyeram-infinity-datasource"
    url: ""
    basicAuth: false
    basicAuthUser: ""
    isDefault: true
    jsonData:
      global_queries: []
    readOnly: false